"""Create

Revision ID: 55ab860ac7ef
Revises: 
Create Date: 2023-02-07 21:58:31.301642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ab860ac7ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coins_created_at'), 'coins', ['created_at'], unique=False)
    op.create_index(op.f('ix_coins_name'), 'coins', ['name'], unique=True)
    op.create_index(op.f('ix_coins_symbol'), 'coins', ['symbol'], unique=True)
    op.create_index(op.f('ix_coins_updated_at'), 'coins', ['updated_at'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_created_at'), 'wallets', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallets_name'), 'wallets', ['name'], unique=True)
    op.create_index(op.f('ix_wallets_updated_at'), 'wallets', ['updated_at'], unique=False)
    op.create_table('wallet_coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_coin')
    op.drop_index(op.f('ix_wallets_updated_at'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_name'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_created_at'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_coins_updated_at'), table_name='coins')
    op.drop_index(op.f('ix_coins_symbol'), table_name='coins')
    op.drop_index(op.f('ix_coins_name'), table_name='coins')
    op.drop_index(op.f('ix_coins_created_at'), table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ###
